name: Nightly Test run (Jahia RL)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests:
    uses:  Jahia/jahia-modules-action/.github/workflows/integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: client-cache-control
      testrail_project: Jahia Client Cache Control Bundle
      pagerduty_incident_service: client-cache-control-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: client-cache-control
      module_branch: ${{ github.ref }}
